### Update gauge metric using json
POST http://localhost:8081/update/
Accept: application/json
Content-Type: application/json

{
  "id": "Alloc",
  "type": "gauge",
  "value": 277777
}

### Update counter metric using json
POST http://localhost:8081/update/
Accept: application/json
Content-Type: application/json

{
  "id": "Count",
  "type": "counter",
  "delta": 0
}

### Update metrics by batch
POST http://localhost:8080/updates/
Accept: application/json
Content-Type: application/json

[
  {
    "id": "Count",
    "type": "counter",
    "delta": 5
  },
  {
    "id": "Alloc",
    "type": "gauge",
    "value": 277777
  }
]

### Get gauge metric as json
POST http://localhost:8081/value/
Accept: application/json
Content-Type: application/json

{
  "id": "Alloc",
  "type": "gauge"
}

### Get counter metric as json
POST http://localhost:8081/value/
Accept: application/json
Content-Type: application/json

{
  "id": "Countsd",
  "type": "counter"
}

### Get all metrics
GET http://localhost:8081/
Content-Type: text/html

### Storage ping
### Get metric as json
GET http://localhost:8081/ping
Accept: text/plain
